# Site settings
title: 내사랑바자회
email: leemiyeong@leevra.com
description: 네이버 중고나라 카페, 일반 마트 만족도 1위 셀러 내사랑바자회 중고마켓, 까페형 중고장터 사이트.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: leevra
permalink: /:title
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/leevra/leevra.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/leevra/leevra.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: leevra
#duoshuo_url: "http://leevra.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: 
disqus_url: "https://ilovebazaar.leeseungju.com"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
